### ISSUE TITLE
Update Homebrew Cask URL

### ISSUE THREAD

**Issue by reitermarkus** [epower/epower.github.com#1]
Hi, we just wanted to let you know that you are still linking to the old Homebrew Cask homepage (`caskroom.io`) in [`2014-07-26-handy-mac-utils.markdown`](https://github.com/epower/epower.github.com/blob/e8ff37690d7aa24bc30c542caa397f30baa14c6d/_posts/2014-07-26-handy-mac-utils.markdown). This domain expired a few years ago and is not controlled by Homebrew anymore.

When you get a chance, please update the link to https://brew.sh/ or https://formulae.brew.sh/cask/.

Thank you,
the Homebrew team.

**Comment by epower** [comment]
no problem - I'll update the post shortly.
